# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6d2fac2b20f8e7e438f037c76e2b5898dfe96db0692130ec37f974697273f2b0023abb2815fc02d461604c121dff184c28dbc89f17a0184a57d4e65c4691a5f

test:
  secret_key_base: 55a4e49279256dced627dcdd5d0a875389b679e662e67cac32092f644eb3a157b97062a85c826ae32acfce0fa9315683c5a057a3a98fdaba255319305a1c7487

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
